# Generated by Django 3.0.4 on 2022-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20220911_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(default=2, max_length=150, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
