# Generated by Django 3.0.4 on 2022-09-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20220911_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
