# Generated by Django 3.0.4 on 2022-09-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_empleado_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='tipo',
            new_name='Tipo',
        ),
    ]
