# Generated by Django 3.0.4 on 2022-09-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20220912_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='Tipo',
        ),
    ]
